import sqlite3
from datetime import datetime

DB_NAME = "ciber_inteligencia.db"
OUTPUT_FILE = "BORRADOR_NEWSLETTER.md"

def generar_newsletter():
    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    # Traemos solo las procesadas (las 10 que viste)
    cursor.execute("SELECT * FROM noticias WHERE ai_processed = 1")
    rows = cursor.fetchall()
    
    # ESTRUCTURA DEL DOCUMENTO
    fecha_hoy = datetime.now().strftime("%B %d, %Y")
    
    contenido = f"""# 🛡️ The Cyber Front - Intelligence Brief
**Date:** {fecha_hoy}
**Status:** ACTIVE THREATS DETECTED

---

## 🚨 Executive Summary (Public)
*Highlights of the most critical threats discovered this week.*

"""
    
    cuerpo_privado = "\n\n--- 💰 PAYWALL BREAK HERE 💰 ---\n\n## 🔐 Classified Analysis (Subscribers Only)\n*Deep dive into technical implications and defense strategies.*\n\n"
    
    count = 0
    for row in rows:
        ai_text = row['ai_summary']
        
        # Saltamos si la IA dijo descartar
        if "DESCARTAR" in ai_text:
            continue
            
        count += 1
        
        # Limpieza simple del texto de la IA (quitamos el "SCORE: X")
        if "SCORE:" in ai_text:
            parts = ai_text.split("ANALISIS:")
            if len(parts) > 1:
                analisis_limpio = parts[1].strip()
            else:
                analisis_limpio = ai_text # Fallback
        else:
            analisis_limpio = ai_text

        # Formateamos cada noticia
        bloque = f"""
### {count}. {row['title']}
**Source:** [{row['source']}]({row['link']})

{analisis_limpio}

---
"""
        # Las primeras 2 noticias van gratis (Gacho), el resto al privado
        if count <= 2:
            contenido += bloque
        else:
            cuerpo_privado += bloque

    # Juntamos todo
    texto_final = contenido + cuerpo_privado + "\n\n_Generated by Cyber-Front AI Engine_"
    
    # Guardamos en archivo
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(texto_final)
    
    conn.close()
    print(f"✅ ¡LISTO! Tu newsletter está en el archivo: {OUTPUT_FILE}")
    print("👉 Abre ese archivo, copia todo y pégalo en el editor de Substack.")

if __name__ == "__main__":
    generar_newsletter()